name: publish
on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: golang:latest
    steps:
    - name: clone
      uses: actions/checkout@v1

    - name: build
      uses: skx/github-action-build@master
      with:
        builder: ./build.sh

    - name: publish
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: target/vela-cli
        cache: true
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
