name: release
on:
  release:
    types: [ created ]

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: golang:latest
    steps:
    - name: clone
      uses: actions/checkout@v1

    - name: build
      uses: skx/github-action-build@master
      with:
        builder: ./build.sh

    - name: upload
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          args: 'release/vela*'
