name: test
on:
  pull_request:
  push:
      
jobs:
  validate:
    name: test
    runs-on: ubuntu-latest
    container:
      image: golang:latest
    steps:
    - name: clone
      uses: actions/checkout@v1
      
    - name: test
      run: |
        go test ./...
